package javadoanmh;

import java.awt.Dimension;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import Encrypt.MD5;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Bussiness.BNhanVien;
import Bussiness.BTaiKhoanNV;
import java.awt.Component;
import java.awt.Toolkit;

public class formMain extends javax.swing.JFrame {

    static String id = "";
    static String maChucVu;
    static String mk = "";
    static Boolean loggedIn = false;
    static inFormNhanVien informNguoiDung;
    static inFormTaiKhoan informTaiKhoan;
    static inFormDoimatKhau informDoiMatKhau;
    static inFormSanPham informSanPham;
    static inFormPhieuNhap informPhieuNhap;
    static inFormPhieuChoThue informPhieuChoThue;
    static inFormDuLieu informDuLieu;
    static inFormPhieuBan informPhieuBan;
    static inFormPhieuTra informPhieuTra;
    static inFormBaoCaoThongKe informBaoCaoThongKe;

    public formMain() {
        initComponents();
        panelLamViec.setVisible(false);
        labelLoiID.setText("");
        labelLoiMatKhau.setText("");
        toolBarManager.setVisible(false);

        informNguoiDung = new inFormNhanVien();
        informTaiKhoan = new inFormTaiKhoan();
        informDoiMatKhau = new inFormDoimatKhau();
        informSanPham = new inFormSanPham();
        informPhieuNhap = new inFormPhieuNhap();
        informPhieuChoThue = new inFormPhieuChoThue();
        informDuLieu = new inFormDuLieu();
        informPhieuBan = new inFormPhieuBan();
        informPhieuTra = new inFormPhieuTra();
        informBaoCaoThongKe = new inFormBaoCaoThongKe();

        informDoiMatKhau.setVisible(false);
        informDoiMatKhau.setName("DoiMatKhau");
        informNguoiDung.setVisible(false);
        informTaiKhoan.setVisible(false);
        informSanPham.setVisible(false);
        informPhieuNhap.setVisible(false);
        informPhieuChoThue.setVisible(false);
        informDuLieu.setVisible(false);
        informPhieuBan.setVisible(false);
        informPhieuTra.setVisible(false);
        informBaoCaoThongKe.setVisible(false);
//        
        panelKhungForm.add(informTaiKhoan);
        panelKhungForm.add(informNguoiDung);
        panelKhungForm.add(informDoiMatKhau);
        panelKhungForm.add(informSanPham);
        panelKhungForm.add(informPhieuNhap);
        panelKhungForm.add(informPhieuChoThue);
        panelKhungForm.add(informDuLieu);
        panelKhungForm.add(informPhieuBan);
        panelKhungForm.add(informPhieuTra);
        panelKhungForm.add(informBaoCaoThongKe);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDangNhap = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/images/shield.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        panelLamViec = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/images/eviroment.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        toolBarManager = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        buttonSanPham = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        buttonPhieuChoThue = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        buttonThem2 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        buttonThem3 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        buttonThem1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        buttonTimKiem = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buttonMatKhau = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        buttonDong = new javax.swing.JButton();
        toolBarChung = new javax.swing.JToolBar();
        panelKhungForm = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/images/none.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        toolBarAdmin = new javax.swing.JToolBar();
        buttonNhanVien = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        buttonTaiKhoan = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        buttonThem6 = new javax.swing.JButton();
        inFrameDangNhap = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        labelLoiID = new javax.swing.JLabel();
        labelLoiMatKhau = new javax.swing.JLabel();
        buttonXoa = new javax.swing.JButton();
        textMatKhau = new javax.swing.JPasswordField();
        buttonOK = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("formMain"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelDangNhap.setAutoscrolls(true);
        panelDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDangNhapMouseClicked(evt);
            }
        });

        panelLamViec.setAutoscrolls(true);
        panelLamViec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelLamViecFocusGained(evt);
            }
        });
        panelLamViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLamViecMouseClicked(evt);
            }
        });

        toolBarManager.setFloatable(false);
        toolBarManager.setRollover(true);
        toolBarManager.setBorderPainted(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order-history-icon (1).png"))); // NOI18N
        jButton2.setText("Phiếu nhập");
        jButton2.setActionCommand("PhieuDatHang");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("PhieuDatHang"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(jButton2);
        toolBarManager.add(jSeparator8);

        buttonSanPham.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSanPham.setForeground(new java.awt.Color(255, 255, 255));
        buttonSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/shipping-box-icon.png"))); // NOI18N
        buttonSanPham.setText("Sản phẩm");
        buttonSanPham.setActionCommand("SanPham");
        buttonSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSanPham.setFocusable(false);
        buttonSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(buttonSanPham);
        toolBarManager.add(jSeparator3);

        buttonPhieuChoThue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPhieuChoThue.setForeground(new java.awt.Color(255, 255, 255));
        buttonPhieuChoThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/basket-icon.png"))); // NOI18N
        buttonPhieuChoThue.setText("Phiếu Thuê");
        buttonPhieuChoThue.setActionCommand("PhieuChoThue");
        buttonPhieuChoThue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPhieuChoThue.setFocusable(false);
        buttonPhieuChoThue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPhieuChoThue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPhieuChoThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(buttonPhieuChoThue);
        toolBarManager.add(jSeparator7);

        buttonThem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonThem2.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/App-wood-box-icon.png"))); // NOI18N
        buttonThem2.setText("Trả Đĩa");
        buttonThem2.setActionCommand("PhieuTra");
        buttonThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem2.setFocusable(false);
        buttonThem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonThem2.setName("PhieuBan"); // NOI18N
        buttonThem2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(buttonThem2);
        toolBarManager.add(jSeparator9);

        buttonThem3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonThem3.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/Column-Chart-icon.png"))); // NOI18N
        buttonThem3.setText("Thống Kê");
        buttonThem3.setActionCommand("BaoCaoThongKe");
        buttonThem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem3.setFocusable(false);
        buttonThem3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonThem3.setName(""); // NOI18N
        buttonThem3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(buttonThem3);
        toolBarManager.add(jSeparator10);

        buttonThem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonThem1.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/shopping-bag-icon.png"))); // NOI18N
        buttonThem1.setText("Bán Đĩa");
        buttonThem1.setActionCommand("PhieuBan");
        buttonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem1.setFocusable(false);
        buttonThem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonThem1.setName("PhieuBan"); // NOI18N
        buttonThem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarManager.add(buttonThem1);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        buttonTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        buttonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        buttonTimKiem.setText("Tìm kiếm");
        buttonTimKiem.setActionCommand("TimKiem");
        buttonTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTimKiem.setFocusable(false);
        buttonTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTimKiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        jToolBar2.add(buttonTimKiem);
        jToolBar2.add(jSeparator4);

        buttonMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        buttonMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-preferences-desktop-user-password-icon.png"))); // NOI18N
        buttonMatKhau.setText("Đổi mật khẩu");
        buttonMatKhau.setActionCommand("DoiMatKhau");
        buttonMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMatKhau.setFocusable(false);
        buttonMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMatKhau.setName("DoiMatKhau"); // NOI18N
        buttonMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        jToolBar2.add(buttonMatKhau);
        jToolBar2.add(jSeparator5);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon.png"))); // NOI18N
        jButton3.setText("Đăng Xuất");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);
        jToolBar2.add(jSeparator6);

        buttonDong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDong.setForeground(new java.awt.Color(255, 255, 255));
        buttonDong.setText("Đóng");
        buttonDong.setFocusable(false);
        buttonDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDongActionPerformed(evt);
            }
        });
        jToolBar2.add(buttonDong);

        toolBarChung.setFloatable(false);
        toolBarChung.setRollover(true);
        toolBarChung.setBorderPainted(false);

        panelKhungForm.setAutoscrolls(true);

        toolBarAdmin.setFloatable(false);
        toolBarAdmin.setRollover(true);
        toolBarAdmin.setBorderPainted(false);

        buttonNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        buttonNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Groups-Meeting-Dark-icon.png"))); // NOI18N
        buttonNhanVien.setText("Nhân viên");
        buttonNhanVien.setActionCommand("NhanVien");
        buttonNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNhanVien.setFocusable(false);
        buttonNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNhanVien.setName("NhanVien"); // NOI18N
        buttonNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarAdmin.add(buttonNhanVien);
        toolBarAdmin.add(jSeparator1);

        buttonTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        buttonTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-user-group-properties-icon.png"))); // NOI18N
        buttonTaiKhoan.setText("Tài khoản");
        buttonTaiKhoan.setActionCommand("TaiKhoan");
        buttonTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTaiKhoan.setFocusable(false);
        buttonTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTaiKhoan.setName("TaiKhoan"); // NOI18N
        buttonTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        toolBarAdmin.add(buttonTaiKhoan);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.add(jSeparator11);

        buttonThem6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonThem6.setForeground(new java.awt.Color(255, 255, 255));
        buttonThem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-basket-icon.png"))); // NOI18N
        buttonThem6.setText("Dữ liệu");
        buttonThem6.setActionCommand("DuLieu");
        buttonThem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThem6.setFocusable(false);
        buttonThem6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonThem6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonThem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });
        jToolBar1.add(buttonThem6);
        buttonThem6.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout panelLamViecLayout = new javax.swing.GroupLayout(panelLamViec);
        panelLamViec.setLayout(panelLamViecLayout);
        panelLamViecLayout.setHorizontalGroup(
            panelLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLamViecLayout.createSequentialGroup()
                .addComponent(toolBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBarManager, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(toolBarChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelKhungForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLamViecLayout.setVerticalGroup(
            panelLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLamViecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolBarChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(toolBarManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolBarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKhungForm, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
        );

        inFrameDangNhap.setClosable(true);
        inFrameDangNhap.setTitle("CHÀO MỪNG");
        inFrameDangNhap.setPreferredSize(new java.awt.Dimension(400, 300));
        inFrameDangNhap.setVisible(true);
        inFrameDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inFrameDangNhapKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        textID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIDFocusLost(evt);
            }
        });
        textID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIDKeyPressed(evt);
            }
        });

        labelLoiID.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        labelLoiID.setForeground(new java.awt.Color(255, 0, 0));
        labelLoiID.setText("Lỗi");

        labelLoiMatKhau.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        labelLoiMatKhau.setForeground(new java.awt.Color(255, 0, 0));
        labelLoiMatKhau.setText("Lỗi");

        buttonXoa.setText("Xóa trắng");
        buttonXoa.setMinimumSize(new java.awt.Dimension(79, 30));
        buttonXoa.setPreferredSize(new java.awt.Dimension(79, 30));
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        textMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textMatKhauFocusGained(evt);
            }
        });
        textMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMatKhauKeyPressed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.setMaximumSize(new java.awt.Dimension(79, 23));
        buttonOK.setMinimumSize(new java.awt.Dimension(79, 30));
        buttonOK.setPreferredSize(new java.awt.Dimension(79, 30));
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonHuy.setText("Hủy bỏ");
        buttonHuy.setMaximumSize(new java.awt.Dimension(79, 23));
        buttonHuy.setMinimumSize(new java.awt.Dimension(79, 30));
        buttonHuy.setPreferredSize(new java.awt.Dimension(79, 23));
        buttonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inFrameDangNhapLayout = new javax.swing.GroupLayout(inFrameDangNhap.getContentPane());
        inFrameDangNhap.getContentPane().setLayout(inFrameDangNhapLayout);
        inFrameDangNhapLayout.setHorizontalGroup(
            inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                        .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel1))
                            .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inFrameDangNhapLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelLoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(labelLoiID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textID)
                                    .addComponent(textMatKhau))))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inFrameDangNhapLayout.setVerticalGroup(
            inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameDangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelLoiID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelLoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inFrameDangNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inFrameDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDangNhapLayout = new javax.swing.GroupLayout(panelDangNhap);
        panelDangNhap.setLayout(panelDangNhapLayout);
        panelDangNhapLayout.setHorizontalGroup(
            panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLamViec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDangNhapLayout.createSequentialGroup()
                    .addGap(0, 540, Short.MAX_VALUE)
                    .addComponent(inFrameDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 558, Short.MAX_VALUE)))
        );
        panelDangNhapLayout.setVerticalGroup(
            panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDangNhapLayout.createSequentialGroup()
                    .addGap(0, 171, Short.MAX_VALUE)
                    .addComponent(inFrameDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 337, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void phanquyenMain() {
        switch (maChucVu) {
            case "GD":
                toolBarAdmin.setVisible(true);
                toolBarManager.setVisible(true);
                break;
            case "Admin":
                toolBarManager.setVisible(false);
                toolBarAdmin.setVisible(true);
                break;
            case "Mana":
                toolBarAdmin.setVisible(false);
                toolBarManager.setVisible(true);
                break;
            default:
                toolBarAdmin.setVisible(false);
                toolBarManager.setVisible(false);
                break;
        }

    }
    private void panelDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDangNhapMouseClicked
        // TODO add your handling code here:

        if (loggedIn == false) {
            if (inFrameDangNhap.isClosed() == false) {
                if (inFrameDangNhap.isVisible()) {
                    inFrameDangNhap.setVisible(false);
                } else {
                    inFrameDangNhap.setVisible(true);
                    textID.requestFocus();
                }
            } else {
                inFrameDangNhap.show();
                try {
                    inFrameDangNhap.setClosed(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                textID.setText("");
                textMatKhau.setText("");
                inFrameDangNhap.setVisible(true);
            }
        }
    }//GEN-LAST:event_panelDangNhapMouseClicked

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        if (textID.getText().equals("")) {

            labelLoiID.setText("Chưa nhập ID!");
            textID.requestFocus();
            // textIDFocusGained);
            return;
        }
        if (new String(textMatKhau.getPassword()).equals("")) {
            labelLoiMatKhau.setText("Chưa nhập mật khẩu!");
            textMatKhau.requestFocus();
            return;
        }
        id = textID.getText();
        BTaiKhoanNV classBTK = new BTaiKhoanNV();
        ResultSet rs = classBTK.getByID(id);
        try {
            if (rs.next()) {
                mk = rs.getString("MatKhauNhanVien").toString();
                if (mk.equals(MD5.getMD5CodeOf(new String(textMatKhau.getPassword())))) {
                    System.out.println("Đăng nhập thành công!");
                    loggedIn = true;
                    inFrameDangNhap.dispose();
                    panelLamViec.setVisible(true);
                    Toolkit t = Toolkit.getDefaultToolkit();
                    Dimension d = t.getScreenSize();
                    this.setSize(d);
                    // this.setLocationByPlatform(true);
                    BNhanVien BND = new BNhanVien("NhanVien");
                    rs = BND.getByID(id);
                    if (rs.next()) {
                        maChucVu = rs.getString("MaChucVu");
                        phanquyenMain();

                        System.out.println("Đăng nhập dưới mã chức vụ: " + maChucVu);
                    }
                } else {
                    labelLoiMatKhau.setText("Mật khẩu không hợp lệ!");
                }
            } else {
                System.out.println("Tài khoản không tồn tại!");
                labelLoiMatKhau.setText("Tài khoản không tồn tại!");
                textIDFocusGained(null);
                textID.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Đăng nhập ngoại lệ: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void textIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusLost
        // TODO add your handling code here:
        if ("".equals(textID.getText())) {
            labelLoiID.setText("Chưa nhập ID!");
        }
    }//GEN-LAST:event_textIDFocusLost

    private void textIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusGained
        // TODO add your handling code here:
        labelLoiID.setText("");
        if (evt != null) {
            labelLoiMatKhau.setText("");
        }
    }//GEN-LAST:event_textIDFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        // TODO add your handling code here:
        textID.setText("");
        textMatKhau.setText("");
        labelLoiID.setText("");
        labelLoiMatKhau.setText("");
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonHuyActionPerformed

    private void textMatKhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatKhauFocusGained
        // TODO add your handling code here:
        labelLoiMatKhau.setText("");
    }//GEN-LAST:event_textMatKhauFocusGained

    private void inFrameDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inFrameDangNhapKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        System.out.println(KeyEvent.getKeyText(key) + " is pressed!");
        if (key == KeyEvent.VK_ENTER) {

            if (textMatKhau.requestFocusInWindow()) {
                buttonOKActionPerformed(null);
            }
        }
    }//GEN-LAST:event_inFrameDangNhapKeyPressed

    private void textMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMatKhauKeyPressed

        System.out.println(KeyEvent.getKeyText(evt.getKeyCode()) + " is pressed!");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonOKActionPerformed(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatKhauKeyPressed

    private void textIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDKeyPressed
        // TODO add your handling code here:

        System.out.println(KeyEvent.getKeyText(evt.getKeyCode()) + " is pressed!");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textMatKhau.requestFocus();
        }
    }//GEN-LAST:event_textIDKeyPressed

    private void panelLamViecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLamViecMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLamViecMouseClicked

    private void panelLamViecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelLamViecFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLamViecFocusGained

    private void Task(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        for (int i = 0; i < panelKhungForm.getComponents().length; i++) {
            Component cmpnt = panelKhungForm.getComponent(i);
            if (cmpnt.getName().equals(command)) {
                cmpnt.setVisible(true);
                if (cmpnt.getName().equals("DoiMatKhau")) {
                    informDoiMatKhau.setTextID(id);
                }
                if (cmpnt.getName().equals("DuLieu")) {
                    inFormDuLieu.phanquyen();
                }
                if (cmpnt.getName().equals("PhieuChoThue")) {
                    informPhieuChoThue.setTextID(id);
                }
                if (cmpnt.getName().equals("PhieuBan")) {
                    informPhieuBan.setTextID(id);
                }
            } else {

                cmpnt.setVisible(false);
            }
        }
    }//GEN-LAST:event_Task

    private void buttonDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDongActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ans == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_buttonDongActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loggedIn = false;
        panelLamViec.setVisible(false);
        panelDangNhap.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDong;
    private javax.swing.JButton buttonHuy;
    private javax.swing.JButton buttonMatKhau;
    private javax.swing.JButton buttonNhanVien;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonPhieuChoThue;
    private javax.swing.JButton buttonSanPham;
    private javax.swing.JButton buttonTaiKhoan;
    private javax.swing.JButton buttonThem1;
    private javax.swing.JButton buttonThem2;
    private javax.swing.JButton buttonThem3;
    private javax.swing.JButton buttonThem6;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JInternalFrame inFrameDangNhap;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel labelLoiID;
    private javax.swing.JLabel labelLoiMatKhau;
    private static javax.swing.JPanel panelDangNhap;
    private javax.swing.JPanel panelKhungForm;
    private static javax.swing.JPanel panelLamViec;
    private javax.swing.JTextField textID;
    private javax.swing.JPasswordField textMatKhau;
    private javax.swing.JToolBar toolBarAdmin;
    private javax.swing.JToolBar toolBarChung;
    private javax.swing.JToolBar toolBarManager;
    // End of variables declaration//GEN-END:variables
}
