/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javadoanmh;

import Bussiness.BPhieuChoThue;
import Bussiness.BSanPham;
import Bussiness.BThanhVien;
import Item.itemPhieuChoThue;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.image.ImageObserver;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.AttributedCharacterIterator;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lvdinh
 */
public class inFormPhieuChoThue extends javax.swing.JInternalFrame {

    ArrayList<itemPhieuChoThue> listPhieuChoThue = new ArrayList<>();
    ArrayList<String> lsCombMaDia = new ArrayList<>();
    ArrayList<String> lsCombThanhVien = new ArrayList<>();
    int madia = -1;

    public inFormPhieuChoThue() {
        initComponents();
        loadCombMaDia();
        loadCombThanhVien();
        buttonOK.setEnabled(false);
        buttonXoa.setEnabled(false);
        lblMaPhieuChoThue.setText("");
        txtMaNhanVien.setEnabled(false);
        lblIDUserHienTai.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        radPhieu = new javax.swing.JRadioButton();
        radChiTietPhieu = new javax.swing.JRadioButton();
        bntTimKiem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSoPhieuThue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuThue = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCTPhieuThue = new javax.swing.JTable();
        combBoxThanhVien = new javax.swing.JComboBox<String>();
        fsdf = new javax.swing.JLabel();
        lableMaDia = new javax.swing.JLabel();
        combBoxMaDia = new javax.swing.JComboBox<String>();
        bntLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntCong = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        lblMaPhieuThue = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        buttonThem = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        lblIDUserHienTai = new javax.swing.JLabel();
        lblNgayThue = new javax.swing.JLabel();
        lblMaPhieuChoThue = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        bntXoaPhieuThue = new javax.swing.JButton();
        bntHoanThanh = new javax.swing.JButton();
        spinSoLuong1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        bntCong1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Phiếu Cho Thuê");
        setName("PhieuChoThue"); // NOI18N

        jLabel3.setText("Tìm kiếm");

        buttonGroup1.add(radPhieu);
        radPhieu.setSelected(true);
        radPhieu.setText("Phiếu thuê");

        buttonGroup1.add(radChiTietPhieu);
        radChiTietPhieu.setText("Chi tiết phiếu thuê");
        radChiTietPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radChiTietPhieuActionPerformed(evt);
            }
        });

        bntTimKiem.setText("Tìm Kiếm");
        bntTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTimKiemActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã Phiếu Thuê:");

        jLabel5.setText("Ngày Lập Phiếu:");

        jLabel6.setText("Mã nhân viên:");

        tablePhieuThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Thuê", " Mã NV", " Mã KH", " Ngày Lập Phiếu", "Ngày Thuê"
            }
        ));
        tablePhieuThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuThue);

        jLabel7.setText("Khách hàng:");

        tableCTPhieuThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đĩa", "Tên đĩa", " Số lượng", "Giá Thuê/Đĩa/Ngày"
            }
        ));
        tableCTPhieuThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCTPhieuThueMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableCTPhieuThue);

        combBoxThanhVien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combBoxThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combBoxThanhVienActionPerformed(evt);
            }
        });

        fsdf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fsdf.setText("Chi Tiết Phiếu Thuê");

        lableMaDia.setText("Mã Đĩa");

        combBoxMaDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bntLamMoi.setText("Làm Mới");
        bntLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLamMoiActionPerformed(evt);
            }
        });

        jLabel1.setText("Số Lượng");

        jLabel8.setText("Mã Phiếu Thuê: ");

        bntCong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntCong.setForeground(new java.awt.Color(51, 51, 255));
        bntCong.setText("+");
        bntCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCongActionPerformed(evt);
            }
        });

        bntXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntXoa.setForeground(new java.awt.Color(255, 0, 0));
        bntXoa.setText("X");
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });

        buttonThem.setText("Thêm");
        buttonThem.setActionCommand("Them");
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });

        buttonSua.setText("Sửa");
        buttonSua.setActionCommand("Sua");
        buttonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaActionPerformed(evt);
            }
        });

        buttonXoa.setText("Hủy ");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        buttonOK.setText("Lưu");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        lblIDUserHienTai.setForeground(new java.awt.Color(255, 51, 0));
        lblIDUserHienTai.setText("MaNVHienTai");

        lblNgayThue.setText("dd/MM/yyyy");

        lblMaPhieuChoThue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaPhieuChoThue.setForeground(new java.awt.Color(0, 0, 204));
        lblMaPhieuChoThue.setText("Mã Phiếu Thuê: ");

        bntXoaPhieuThue.setText("Xóa");

        bntHoanThanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/print-printer.png"))); // NOI18N
        bntHoanThanh.setText("In Phiếu Thuê");
        bntHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHoanThanhActionPerformed(evt);
            }
        });

        jLabel2.setText("Số Lượng");

        bntCong1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntCong1.setForeground(new java.awt.Color(51, 255, 51));
        bntCong1.setText("-");
        bntCong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCong1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fsdf, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radPhieu)
                            .addComponent(radChiTietPhieu))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(lblTenNhanVien)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(bntTimKiem)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bntLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(bntHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lableMaDia)
                                        .addGap(10, 10, 10)
                                        .addComponent(combBoxMaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntCong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bntCong1)
                                        .addGap(14, 14, 14)
                                        .addComponent(bntXoa))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(541, 541, 541)
                                        .addComponent(lblMaPhieuThue))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblMaPhieuChoThue))
                                            .addComponent(jScrollPane3))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblIDUserHienTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(16, 16, 16)
                                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNgayThue)
                                            .addComponent(combBoxThanhVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSoPhieuThue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spinSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(buttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(buttonSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(bntXoaPhieuThue, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel3))
                                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addComponent(fsdf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radPhieu)
                                        .addGap(3, 3, 3)
                                        .addComponent(radChiTietPhieu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblMaPhieuChoThue))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaPhieuThue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lableMaDia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(combBoxMaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bntXoa)
                                .addComponent(bntCong1)
                                .addComponent(bntCong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntHoanThanh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblTenNhanVien)
                        .addGap(18, 18, 18)
                        .addComponent(lblIDUserHienTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSoPhieuThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblNgayThue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combBoxThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonThem)
                            .addComponent(buttonSua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonXoa)
                            .addComponent(buttonOK))
                        .addGap(7, 7, 7)
                        .addComponent(bntXoaPhieuThue)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayDataPhieuNhapHang(ResultSet rs) {
        listPhieuChoThue.clear();
        DefaultTableModel model = (DefaultTableModel) tablePhieuThue.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                itemPhieuChoThue item = new itemPhieuChoThue(
                        rs.getInt("SoPhieuThue"),
                        rs.getString("TenNhanVien"),
                        rs.getString("TenThanhVien"),
                        rs.getString("NgayThue"),
                        rs.getString("MaKH"),
                        rs.getString("MaNV"),
                        rs.getInt("SoluongNgayThue")
                );
                listPhieuChoThue.add(item);

                Vector vector = new Vector();
                vector.add(item.getSoPhieuThue());
                vector.add(item.getTenKhachHang());
                vector.add(item.getTenNhanVien());
                vector.add(item.getNgayThue());
                vector.add(item.getSoLuongNgayThue());

                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataPhieuNhap 2: " + ex.getMessage());
        }
    }

    private void bntLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLamMoiActionPerformed
        // TODO add your handling code here:
        BPhieuChoThue BPN = new BPhieuChoThue();
        ResultSet rs = BPN.getAll();
        displayDataPhieuNhapHang(rs);
        tableCTPhieuThue.removeAll();

        loadCombThanhVien();
        loadCombMaDia();
    }//GEN-LAST:event_bntLamMoiActionPerformed

    private void tablePhieuThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuThueMouseClicked
        int index = tablePhieuThue.getSelectedRow();

        int sophieuthue = Integer.parseInt(tablePhieuThue.getValueAt(index, 0).toString());

        lblMaPhieuChoThue.setText(String.valueOf(sophieuthue));

        BPhieuChoThue BPN = new BPhieuChoThue();

        ResultSet rs = BPN.GetCTPTByPhieuThueID(sophieuthue);
        displayDataChiTietPhieuThue(rs);

        txtSoPhieuThue.setText(String.valueOf(listPhieuChoThue.get(index).getSoPhieuThue()));

        combBoxThanhVien.setSelectedItem(listPhieuChoThue.get(index).getTenKhachHang());

        txtMaNhanVien.setText(listPhieuChoThue.get(index).getMaNV());

        lblNgayThue.setText(listPhieuChoThue.get(index).getNgayThue());
    }//GEN-LAST:event_tablePhieuThueMouseClicked

    private void bntCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCongActionPerformed
        // TODO add your handling code here:
        int madia = 0;
        try {
            madia = Integer.parseInt(lsCombMaDia.get(combBoxMaDia.getSelectedIndex()));

        } catch (Exception ex) {
            madia = 0;
        }
        if (madia > 0) {
            try {
                int index = tablePhieuThue.getSelectedRow();

                int sophieuthue = Integer.parseInt(tablePhieuThue.getValueAt(index, 0).toString());
                BPhieuChoThue BPDH = new BPhieuChoThue();
                int soluong = 0;

                try {
                    soluong = (int) this.spinSoLuong.getValue();

                } catch (Exception ex) {
                    soluong = 0;
                }
                if (soluong != 0) {
                    if (BPDH.CapNhatSoLuongCTPT(sophieuthue, soluong, madia)) {
                        ResultSet rs = BPDH.GetCTPTByPhieuThueID(sophieuthue);
                        displayDataChiTietPhieuThue(rs);

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ Số lượng Khác 0", "Lỗi!", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(inFormPhieuBan.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Loi" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_bntCongActionPerformed

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        // TODO add your handling code here:
        int MaDia = 0;
        int row = tableCTPhieuThue.getSelectedRow();
        try {
            MaDia = Integer.parseInt(tableCTPhieuThue.getValueAt(row, 0).toString());
            int index = tablePhieuThue.getSelectedRow();
            int sophieuthue = Integer.parseInt(tablePhieuThue.getValueAt(index, 0).toString());
            BPhieuChoThue BPDH = new BPhieuChoThue();
            if (BPDH.deleteMaDiaChiTietPhieuThue(sophieuthue, MaDia)) {
                ResultSet rs = BPDH.GetCTPTByPhieuThueID(sophieuthue);
                displayDataChiTietPhieuThue(rs);
            } else {
                System.out.println("Loi Xoa Khong Thanh Công!");

            }
        } catch (Exception ex) {
            System.out.println("Loi Khi Xoa: " + ex.getMessage());
        }

    }//GEN-LAST:event_bntXoaActionPerformed

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        buttonOK.setEnabled(true);
        buttonXoa.setEnabled(true);
        buttonThem.setEnabled(false);
        buttonSua.setEnabled(false);
        txtSoPhieuThue.setText("");
        txtMaNhanVien.setText("");
        lblNgayThue.setText("");
    }//GEN-LAST:event_buttonThemActionPerformed

    private void buttonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaActionPerformed

        int index = tablePhieuThue.getSelectedRow();
        String matv = lsCombThanhVien.get(combBoxThanhVien.getSelectedIndex());
        String manhanvien = txtMaNhanVien.getText();
        String ngaylapphieu = lblNgayThue.getText();
        int sophieuthue = listPhieuChoThue.get(index).getSoPhieuThue();
        int soluongngay = Integer.parseInt(this.spinSoLuong1.getValue().toString());
        if (soluongngay <= 0) {
            JOptionPane.showMessageDialog(this, "Số Lượng ngày thuê phải lớn hơn 0", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        BPhieuChoThue BPN = new BPhieuChoThue();
        if (BPN.updateByProperties(sophieuthue, ngaylapphieu, matv, manhanvien, soluongngay)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Đã cập nhật!", JOptionPane.INFORMATION_MESSAGE);
            bntLamMoiActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi trong khi cập nhật!", "Chưa cập nhật!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonSuaActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        buttonOK.setEnabled(false);
        buttonXoa.setEnabled(false);
        buttonThem.setEnabled(true);
        buttonSua.setEnabled(true);
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
//        this.dispose();
//        this.setVisible(false);
        try {
            BPhieuChoThue BPN = new BPhieuChoThue();
            Date today = new Date(System.currentTimeMillis());
            SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss dd/MM/yyyy");
            String ngaylapphieu = timeFormat.format(today.getTime());
            int soluongngay = Integer.parseInt(this.spinSoLuong1.getValue().toString());
            if (soluongngay <= 0) {
                JOptionPane.showMessageDialog(this, "Số Lượng ngày thuê phải lớn hơn 0", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (txtSoPhieuThue.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không bỏ trống mã phiếu cho thuê!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (BPN.insertByProperties(Integer.parseInt(txtSoPhieuThue.getText()), ngaylapphieu,
                    lsCombThanhVien.get(combBoxThanhVien.getSelectedIndex()), lblIDUserHienTai.getText(), soluongngay)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm", JOptionPane.INFORMATION_MESSAGE);
                bntLamMoiActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã tồn tại!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã phiếu nhập phải là số!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
        }
        buttonOK.setEnabled(false);
        buttonXoa.setEnabled(false);
        buttonThem.setEnabled(true);
        buttonSua.setEnabled(true);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void bntTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTimKiemActionPerformed
        // TODO add your handling code here:
        BPhieuChoThue BPN = new BPhieuChoThue();
        if (radPhieu.isSelected()) {
            ResultSet rs = BPN.searchAllPhieuThue(txtTimKiem.getText());
            displayDataPhieuNhapHang(rs);
        } else if (tablePhieuThue.getSelectedRow() >= 0) {
            ResultSet rs = BPN.searchAllChiTietPhieuThue(String.valueOf(listPhieuChoThue.get(tablePhieuThue.getSelectedRow()).getSoPhieuThue()), txtTimKiem.getText());
            displayDataChiTietPhieuThue(rs);
        }
    }//GEN-LAST:event_bntTimKiemActionPerformed

    private void radChiTietPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radChiTietPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radChiTietPhieuActionPerformed

    private void combBoxThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combBoxThanhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combBoxThanhVienActionPerformed

    private void bntCong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCong1ActionPerformed
        // TODO add your handling code here:

        if (madia > 0) {
            try {
                int index = tablePhieuThue.getSelectedRow();
                int index2 = tableCTPhieuThue.getSelectedRow();

                int sophieuthue = Integer.parseInt(tablePhieuThue.getValueAt(index, 0).toString());
                BPhieuChoThue BPDH = new BPhieuChoThue();
                int soluong = 0;

                try {
                    soluong = (int) this.spinSoLuong.getValue() * -1;

                } catch (Exception ex) {
                    soluong = 0;
                }
                if (soluong != 0 && Integer.parseInt(tableCTPhieuThue.getValueAt(index2, 2).toString()) > soluong * -1) {
                    if (BPDH.CapNhatSoLuongCTPT(sophieuthue, soluong, madia)) {
                        ResultSet rs = BPDH.GetCTPTByPhieuThueID(sophieuthue);
                        displayDataChiTietPhieuThue(rs);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ: so luong Khac 0 Hoặc < số lượng hiện có", "Lỗi!", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(inFormPhieuBan.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Loi" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_bntCong1ActionPerformed

    private void tableCTPhieuThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTPhieuThueMouseClicked
        try {
            int row = this.tableCTPhieuThue.getSelectedRow();
            madia = Integer.parseInt((this.tableCTPhieuThue.getValueAt(row, 0).toString()));
        } catch (Exception ex) {
            madia = -1;
        }
        if (madia != -1) {
            this.bntCong1.setEnabled(true);
        } else {
            this.bntCong1.setEnabled(false);
        }

    }//GEN-LAST:event_tableCTPhieuThueMouseClicked

    private void bntHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHoanThanhActionPerformed
        try {
          

            this.tableCTPhieuThue.print();
        } catch (PrinterException ex) {
            Logger.getLogger(inFormPhieuChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bntHoanThanhActionPerformed

    private void loadCombMaDia() {
        combBoxMaDia.removeAllItems();
        lsCombMaDia.clear();
        BSanPham BSP = new BSanPham();
        ResultSet rs = BSP.getAllMaDia();
        try {
            while (rs.next()) {
                combBoxMaDia.addItem(rs.getString("TenDia"));
                lsCombMaDia.add(rs.getString("MaDia"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCombThanhVien() {
        combBoxThanhVien.removeAllItems();
        lsCombThanhVien.clear();
        BThanhVien BNV = new BThanhVien();
        ResultSet rs = BNV.getBaseProperties();
        try {
            while (rs.next()) {
                combBoxThanhVien.addItem(rs.getString("TenThanhVien"));
                lsCombThanhVien.add(rs.getString("MaThanhVien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuChoThue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void displayDataChiTietPhieuThue(ResultSet rs) {
        DefaultTableModel model = (DefaultTableModel) tableCTPhieuThue.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {

                Vector vector = new Vector();
                vector.add(rs.getString("MaDia"));
                vector.add(rs.getString("TenDia"));
                vector.add(rs.getString("SoLuong"));
                vector.add(rs.getString("DonGia"));
                model.addRow(vector);

            }
            Vector summaryvector = new Vector();

            int row = tableCTPhieuThue.getRowCount();

            int index = tablePhieuThue.getSelectedRow();

            int Ngaymuon = Integer.parseInt(tablePhieuThue.getValueAt(index, 4).toString());

            double tongtien = 0;
            for (int i = 0; i < row; i++) {
                int soluong = Integer.parseInt(tableCTPhieuThue.getValueAt(i, 2).toString());
                double DonGia = Double.parseDouble(tableCTPhieuThue.getValueAt(i, 3).toString());
                tongtien += soluong * DonGia * Ngaymuon;
            }

            String hoTenKhach = tablePhieuThue.getValueAt(index, 2).toString();

            summaryvector.add("Tổng Tiền: ");

            summaryvector.add(hoTenKhach);
            summaryvector.add(" ");
            summaryvector.add(tongtien);

            model.addRow(summaryvector);
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataChiTietPhieuThue 2: " + ex.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCong;
    private javax.swing.JButton bntCong1;
    private javax.swing.JButton bntHoanThanh;
    private javax.swing.JButton bntLamMoi;
    private javax.swing.JButton bntTimKiem;
    private javax.swing.JButton bntXoa;
    private javax.swing.JButton bntXoaPhieuThue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JComboBox<String> combBoxMaDia;
    private javax.swing.JComboBox<String> combBoxThanhVien;
    private javax.swing.JLabel fsdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lableMaDia;
    private javax.swing.JLabel lblIDUserHienTai;
    private javax.swing.JLabel lblMaPhieuChoThue;
    private javax.swing.JLabel lblMaPhieuThue;
    private javax.swing.JLabel lblNgayThue;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JRadioButton radChiTietPhieu;
    private javax.swing.JRadioButton radPhieu;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JSpinner spinSoLuong1;
    private javax.swing.JTable tableCTPhieuThue;
    private javax.swing.JTable tablePhieuThue;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoPhieuThue;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
public void setTextID(String id) {
        lblIDUserHienTai.setText(id);
    }
}
