/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javadoanmh;

import Bussiness.BTaiKhoanNV;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lvdinh
 */
public class inFormDoimatKhau extends javax.swing.JInternalFrame {

    /**
     * Creates new form inFrameDoiMatKhau
     */
    public inFormDoimatKhau() {

        initComponents();

        buttonXoaTrangActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textMatKhauCu = new javax.swing.JPasswordField();
        textMatKhauMoi = new javax.swing.JPasswordField();
        labelLoiMatKhauMoi = new javax.swing.JLabel();
        labelLoiMatKhauCu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNhapLaiMatKhauMoi = new javax.swing.JPasswordField();
        buttonOK = new javax.swing.JButton();
        buttonXoaTrang = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();
        labelLoiNhapLaiMatKhauMoi = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Thay đổi mật khẩu");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-preferences-desktop-user-password-icon.png"))); // NOI18N
        setName("DoiMatKhau"); // NOI18N

        jLabel1.setText("ID");

        jLabel3.setText("Mật khẩu cũ");

        jLabel4.setText("Mật khẩu mới");

        textID.setEnabled(false);
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        textMatKhauCu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textMatKhauCuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMatKhauCuFocusLost(evt);
            }
        });
        textMatKhauCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMatKhauCuKeyPressed(evt);
            }
        });

        textMatKhauMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textMatKhauMoiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMatKhauMoiFocusLost(evt);
            }
        });
        textMatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMatKhauMoiKeyPressed(evt);
            }
        });

        labelLoiMatKhauMoi.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelLoiMatKhauMoi.setForeground(new java.awt.Color(255, 51, 51));
        labelLoiMatKhauMoi.setText("Lỗi");

        labelLoiMatKhauCu.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelLoiMatKhauCu.setForeground(new java.awt.Color(255, 51, 51));
        labelLoiMatKhauCu.setText("Lỗi");

        jLabel8.setText("Nhập lại mật khẩu mới");

        textNhapLaiMatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNhapLaiMatKhauMoiKeyPressed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonXoaTrang.setText("Xóa trắng");
        buttonXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaTrangActionPerformed(evt);
            }
        });

        buttonHuy.setText("Hủy");
        buttonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyActionPerformed(evt);
            }
        });

        labelLoiNhapLaiMatKhauMoi.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelLoiNhapLaiMatKhauMoi.setForeground(new java.awt.Color(255, 51, 51));
        labelLoiNhapLaiMatKhauMoi.setText("Lỗi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonXoaTrang)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLoiMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLoiNhapLaiMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(labelLoiMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textMatKhauCu)
                            .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(textNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLoiMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLoiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelLoiNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonXoaTrang)
                    .addComponent(buttonHuy)
                    .addComponent(buttonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void buttonXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaTrangActionPerformed
        // TODO add your handling code here:
        textMatKhauCu.setText("");
        textNhapLaiMatKhauMoi.setText("");
        textMatKhauMoi.setText("");

        labelLoiMatKhauCu.setText("");
        labelLoiMatKhauMoi.setText("");
        labelLoiNhapLaiMatKhauMoi.setText("");

        textMatKhauCu.requestFocus();
    }//GEN-LAST:event_buttonXoaTrangActionPerformed

    private void buttonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyActionPerformed
        buttonXoaTrangActionPerformed(evt);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHuyActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        String pw = new String(textMatKhauCu.getPassword());
        if (pw.equals("")) {
            labelLoiMatKhauCu.setText("Chưa nhập mật khẩu cũ!");
            textMatKhauMoi.requestFocus();
            return;
        }
        String pw1 = new String(textMatKhauMoi.getPassword());
        if (pw1.equals("")) {
            labelLoiMatKhauMoi.setText("Chưa nhập mật khẩu mới!");
            textMatKhauMoi.requestFocus();
            return;
        }
        String pw2 = new String(textNhapLaiMatKhauMoi.getPassword());
        if (pw2.equals("")) {
            labelLoiNhapLaiMatKhauMoi.setText("Chưa nhập lại mật khẩu mới!");
            textNhapLaiMatKhauMoi.requestFocus();
            return;
        }

        if (!pw1.equals(pw2)) {
            labelLoiNhapLaiMatKhauMoi.setText("Mật khẩu mới không trùng nhau!");
            textNhapLaiMatKhauMoi.requestFocus();
            return;
        }
        BTaiKhoanNV BTKNV = new BTaiKhoanNV();
        ResultSet rs = BTKNV.getByID(textID.getText());
        try {
            if (rs.next()) {
                String mk = rs.getString("MatKhauNhanVien");
                if (mk.equals(Encrypt.MD5.getMD5CodeOf(pw))) {
                    if (BTKNV.updateByProperties(textID.getText(), Encrypt.MD5.getMD5CodeOf(pw1))) {
                        JOptionPane.showMessageDialog(this, "Mật khẩu đã thay đổi!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Có lỗi khi thay đổi mật khẩu!", "Lỗi khi thay đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
                        System.out.print("Có lỗi khi thay đổi mật khẩu!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDoimatKhau.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void textMatKhauCuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatKhauCuFocusLost
        if ((new String(textMatKhauCu.getPassword())).equals("")) {
            labelLoiMatKhauCu.setText("Chưa nhập mật khẩu cũ!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatKhauCuFocusLost

    private void textMatKhauMoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatKhauMoiFocusGained
        labelLoiMatKhauMoi.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatKhauMoiFocusGained

    private void textMatKhauCuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatKhauCuFocusGained
        // TODO add your handling code here:
        labelLoiMatKhauCu.setText("");
    }//GEN-LAST:event_textMatKhauCuFocusGained

    private void textMatKhauMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatKhauMoiFocusLost
        // TODO add your handling code here:
        if ((new String(textMatKhauMoi.getPassword())).equals("")) {
            labelLoiMatKhauMoi.setText("Chưa nhập mật khẩu mới!");
        }
    }//GEN-LAST:event_textMatKhauMoiFocusLost

    private void textMatKhauCuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMatKhauCuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textMatKhauMoi.requestFocus();
        }
    }//GEN-LAST:event_textMatKhauCuKeyPressed

    private void textMatKhauMoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMatKhauMoiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textNhapLaiMatKhauMoi.requestFocus();
        }
    }//GEN-LAST:event_textMatKhauMoiKeyPressed

    private void textNhapLaiMatKhauMoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNhapLaiMatKhauMoiKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            buttonOKActionPerformed(null);
        }
        if (key == KeyEvent.VK_ESCAPE) {
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_textNhapLaiMatKhauMoiKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHuy;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonXoaTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelLoiMatKhauCu;
    private javax.swing.JLabel labelLoiMatKhauMoi;
    private javax.swing.JLabel labelLoiNhapLaiMatKhauMoi;
    private javax.swing.JTextField textID;
    private javax.swing.JPasswordField textMatKhauCu;
    private javax.swing.JPasswordField textMatKhauMoi;
    private javax.swing.JPasswordField textNhapLaiMatKhauMoi;
    // End of variables declaration//GEN-END:variables

    public void setTextID(String id) {
        textID.setText(id);
    }
}
