/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javadoanmh;

import Bussiness.BNhaCungCap;
import Bussiness.BNhanVien;
import Bussiness.BPhieuNhap;
import Bussiness.BSanPham;
import Item.itemPhieuNhap;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class inFormPhieuNhap extends javax.swing.JInternalFrame {

    ArrayList<itemPhieuNhap> listPhieuNhap = new ArrayList<>();
    ArrayList<String> lsCombNhaCungCap = new ArrayList<>();
    ArrayList<String> lsCombNhanVien = new ArrayList<>();
    ArrayList<String> lsCombMaDia = new ArrayList<>();

    public inFormPhieuNhap() {
        initComponents();
        loadCombNhaCungCap();
        loadCombNhanVien();
        loadCombMaDia();
        buttonOK.setEnabled(false);
        buttonXoa.setEnabled(false);
        buttonLamMoiActionPerformed(null);
        textTimKiem.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                buttonTimKiemActionPerformed(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuNhap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietPhieuNhap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonLamMoi = new javax.swing.JButton();
        buttonTimKiem = new javax.swing.JButton();
        textTimKiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radPhieu = new javax.swing.JRadioButton();
        radChiTietPhieu = new javax.swing.JRadioButton();
        buttonOK = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonThem = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combTenNhanVien = new javax.swing.JComboBox();
        combNhaCungCap = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        combMaDia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        buttonCong = new javax.swing.JButton();
        buttonTru = new javax.swing.JButton();
        labelTenPhieu = new javax.swing.JLabel();
        buttonX = new javax.swing.JButton();
        ftextMaPhieuNhap = new javax.swing.JTextField();
        lblNgayLapPhieu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Phiếu nhập hàng");
        setName("PhieuDatHang"); // NOI18N

        tablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập hàng", "Nhà cung cấp", "Tên nhân viên lập phiếu nhập ", "Ngày lập phiếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuNhap);

        tableChiTietPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đĩa", "Tên Đĩa", "Số lượng ", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableChiTietPhieuNhap);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chi tiết phiếu nhập hàng");

        jLabel2.setText("Mã phiếu nhập hàng");

        jLabel4.setText("Tên nhân viên");

        jLabel5.setText("Ngày lập phiếu");

        buttonLamMoi.setText("Làm mới");
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        buttonTimKiem.setText("Tìm kiếm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm");

        buttonGroup1.add(radPhieu);
        radPhieu.setSelected(true);
        radPhieu.setText("Phiếu nhập hàng");

        buttonGroup1.add(radChiTietPhieu);
        radChiTietPhieu.setText("Chi tiết phiếu nhập hàng");
        radChiTietPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radChiTietPhieuActionPerformed(evt);
            }
        });

        buttonOK.setText("Lưu");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonXoa.setText("Hủy");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        buttonThem.setText("Thêm");
        buttonThem.setActionCommand("Them");
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });

        buttonSua.setText("Sửa");
        buttonSua.setActionCommand("Sua");
        buttonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhà cung cấp");

        jButton1.setText("Mới");

        jLabel7.setText("Mã đĩa");

        jLabel8.setText("Số lượng");

        spinSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        buttonCong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonCong.setForeground(new java.awt.Color(51, 255, 51));
        buttonCong.setText("+");
        buttonCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCongActionPerformed(evt);
            }
        });

        buttonTru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTru.setForeground(new java.awt.Color(255, 204, 0));
        buttonTru.setText("-");
        buttonTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTruActionPerformed(evt);
            }
        });

        labelTenPhieu.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelTenPhieu.setForeground(new java.awt.Color(0, 0, 204));

        buttonX.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        buttonX.setForeground(new java.awt.Color(204, 0, 0));
        buttonX.setText("X");
        buttonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXActionPerformed(evt);
            }
        });

        lblNgayLapPhieu.setText("dd/MM/yyyy");

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelTenPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(582, 582, 582))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(combMaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(buttonCong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(radChiTietPhieu)
                                                    .addComponent(radPhieu))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonTru)
                                                .addGap(29, 29, 29)
                                                .addComponent(buttonX)
                                                .addGap(11, 11, 11))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(buttonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(buttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(buttonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(combTenNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(combNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ftextMaPhieuNhap)
                                            .addComponent(lblNgayLapPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(radChiTietPhieu))
                        .addComponent(radPhieu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTenPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combMaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCong)
                            .addComponent(buttonTru)
                            .addComponent(buttonX))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ftextMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblNgayLapPhieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(buttonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayDataPhieuNhapHang(ResultSet rs) {
        listPhieuNhap.clear();
        DefaultTableModel model = (DefaultTableModel) tablePhieuNhap.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                itemPhieuNhap item = new itemPhieuNhap(rs.getInt("SoPhieuNhap"), rs.getString("TenNhaCC"), rs.getString("TenNhanVien"),
                        rs.getString("NgayNhap"));
                listPhieuNhap.add(item);

                Vector vector = new Vector();
                vector.add(item.getSoPhieuNhap());
                vector.add(item.getTenNhaCC());
                vector.add(item.getTenNhanVien());
                vector.add(item.getNgayLap());

                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataPhieuNhap 2: " + ex.getMessage());
        }
    }

    private void displayDataChiTietPhieuNhap(ResultSet rs) {
        DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuNhap.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {

                Vector vector = new Vector();
                vector.add(rs.getInt("MaDia"));
                vector.add(rs.getString("TenDia"));
                vector.add(rs.getInt("SoLuong"));
                vector.add(rs.getBigDecimal("DonGia"));
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataChiTietPhieuNhap 2: " + ex.getMessage());
        }
    }

    private void loadCombNhaCungCap() {
        combNhaCungCap.removeAllItems();
        lsCombNhaCungCap.clear();
        BNhaCungCap BNCC = new BNhaCungCap();
        ResultSet rs = BNCC.getAll();
        try {
            while (rs.next()) {
                combNhaCungCap.addItem(rs.getString("TenNhaCC"));
                lsCombNhaCungCap.add(rs.getString("MaNhaCC"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCombNhanVien() {
        combTenNhanVien.removeAllItems();
        lsCombNhanVien.clear();
        BNhanVien BNV = new BNhanVien();
        ResultSet rs = BNV.getAllNhanVienXN();
        try {
            while (rs.next()) {
                combTenNhanVien.addItem(rs.getString("TenNhanVien"));
                lsCombNhanVien.add(rs.getString("MaNhanVien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCombMaDia() {
        combMaDia.removeAllItems();
        lsCombMaDia.clear();
        BSanPham BSP = new BSanPham();
        ResultSet rs = BSP.getAllMaDia();
        try {
            while (rs.next()) {
                combMaDia.addItem(rs.getString("MaDia"));
                lsCombMaDia.add(rs.getString("TenDia"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void radChiTietPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radChiTietPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radChiTietPhieuActionPerformed

    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        BPhieuNhap BPN = new BPhieuNhap();
        ResultSet rs = BPN.getAll();
        displayDataPhieuNhapHang(rs);
        tableChiTietPhieuNhap.removeAll();

        loadCombNhaCungCap();
        loadCombNhanVien();
        loadCombMaDia();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLamMoiActionPerformed

    private void tablePhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuNhapMouseClicked
        int index = tablePhieuNhap.getSelectedRow();

        int sophieunhap = listPhieuNhap.get(index).getSoPhieuNhap();

        labelTenPhieu.setText(String.valueOf(sophieunhap));

        BPhieuNhap BPN = new BPhieuNhap();
        ResultSet rs = BPN.getChiTietPhieuNhap(sophieunhap);
        displayDataChiTietPhieuNhap(rs);

        ftextMaPhieuNhap.setText(String.valueOf(listPhieuNhap.get(index).getSoPhieuNhap()));

        combNhaCungCap.setSelectedItem(listPhieuNhap.get(index).getTenNhaCC());
        combTenNhanVien.setSelectedItem(listPhieuNhap.get(index).getTenNhanVien());
        lblNgayLapPhieu.setText(listPhieuNhap.get(index).getNgayLap());
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePhieuNhapMouseClicked

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        Date today = new Date(System.currentTimeMillis());
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss dd/MM/yyyy");
        lblNgayLapPhieu.setText(timeFormat.format(today.getTime()));
        buttonThem.setEnabled(false);
        buttonOK.setEnabled(true);
        buttonSua.setEnabled(false);
        ftextMaPhieuNhap.setText("");
        buttonXoa.setEnabled(true);
        //lblNgayLapPhieu.setText("");
    }//GEN-LAST:event_buttonThemActionPerformed

    private void buttonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaActionPerformed

        int index = tablePhieuNhap.getSelectedRow();
        int manhacungcap = Integer.parseInt(lsCombNhaCungCap.get(combNhaCungCap.getSelectedIndex()));
        String manhanvien = lsCombNhanVien.get(combTenNhanVien.getSelectedIndex());
        String ngaylapphieu = listPhieuNhap.get(index).getNgayLap();
        int sophieunhap = listPhieuNhap.get(index).getSoPhieuNhap();

        BPhieuNhap BPN = new BPhieuNhap();
        if (BPN.updateByProperties(sophieunhap, manhacungcap, manhanvien, ngaylapphieu)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Đã cập nhật!", JOptionPane.INFORMATION_MESSAGE);
            buttonLamMoiActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã tồn tại!", "Chưa cập nhật!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonSuaActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        try {
            BPhieuNhap BPN = new BPhieuNhap();

            if (ftextMaPhieuNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không để trống mã phiếu nhập!", "lỗi!", JOptionPane.INFORMATION_MESSAGE);
            } else if (BPN.insertByProperties(Integer.parseInt(ftextMaPhieuNhap.getText()), Integer.parseInt(lsCombNhaCungCap.get(combNhaCungCap.getSelectedIndex())),
                    lsCombNhanVien.get(combTenNhanVien.getSelectedIndex()), lblNgayLapPhieu.getText())) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm", JOptionPane.INFORMATION_MESSAGE);
                buttonLamMoiActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã tồn tại!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã phiếu nhập phải là số!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
        }
        buttonThem.setEnabled(true);
        buttonOK.setEnabled(false);
        buttonSua.setEnabled(true);
        buttonXoa.setEnabled(false);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        ftextMaPhieuNhap.setText("");
        buttonThem.setEnabled(true);
        buttonOK.setEnabled(false);
        buttonSua.setEnabled(true);
        buttonXoa.setEnabled(false);
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCongActionPerformed
        int madia = Integer.parseInt(combMaDia.getSelectedItem().toString());
        String md = String.valueOf(madia);
        if (!md.isEmpty()) {
            int index = tablePhieuNhap.getSelectedRow();

            int sophieunhap = listPhieuNhap.get(index).getSoPhieuNhap();
            BPhieuNhap BPDH = new BPhieuNhap();
            int soluong = (int) spinSoLuong.getValue();
            if (soluong > 0 && BPDH.insertChiTietPhieuNhap(sophieunhap, madia, soluong, BigDecimal.ONE)) {

                ResultSet rs = BPDH.getChiTietPhieuNhap(sophieunhap);
                displayDataChiTietPhieuNhap(rs);
            } //JOptionPane.showMessageDialog(this, "Them", "them", JOptionPane.INFORMATION_MESSAGE);
            else {
                JOptionPane.showMessageDialog(this, "Lỗi khi thêm linh kiện!", "Lỗi!", JOptionPane.INFORMATION_MESSAGE);
            }
            //tablePhieuDatHangMouseClicked(null);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCongActionPerformed

    @SuppressWarnings("empty-statement")
    private void buttonTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTruActionPerformed
        // TODO add your handling code here:
        int index = tableChiTietPhieuNhap.getSelectedRow();
        if (index >= 0) {
            DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuNhap.getModel();
            int madia = Integer.parseInt(model.getValueAt(index, 0).toString());
            int soluong = Integer.parseInt(model.getValueAt(index, 2).toString());
            int giatri = Integer.parseInt(spinSoLuong.getValue().toString());
            //System.out.print("-"+soluong);
            int i = soluong - giatri;
            if (i >= 0) {
                //giam so luong di 1
                int index2 = tablePhieuNhap.getSelectedRow();
                if (index2 >= 0) {
                    int sophieunhap = listPhieuNhap.get(index2).getSoPhieuNhap();
                    BPhieuNhap BPN = new BPhieuNhap();
                    if (BPN.updateSoLuongChiTietPhieuNhap(sophieunhap, madia, i)) {
                        //reload
                        BPhieuNhap BPD = new BPhieuNhap();
                        ResultSet rs = BPD.getChiTietPhieuNhap(sophieunhap);
                        displayDataChiTietPhieuNhap(rs);
                        System.out.println("Bớt số lượng thành công!");
                    } else {
                        System.out.print("Bớt số lượng bị lỗi!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Trừ quá số lượng!", "Không được!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_buttonTruActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
        int index = tableChiTietPhieuNhap.getSelectedRow();
        if (index >= 0) {
            DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuNhap.getModel();
            int madia = Integer.parseInt(model.getValueAt(index, 0).toString());
            int index2 = tablePhieuNhap.getSelectedRow();
            if (index2 >= 0) {
                int sophieunhap = listPhieuNhap.get(index2).getSoPhieuNhap();
                BPhieuNhap BPN = new BPhieuNhap();
                if (BPN.deleteMaDiaChiTietPhieuNhap(sophieunhap, madia)) {
                    //reload
                    BPhieuNhap BPD = new BPhieuNhap();
                    ResultSet rs = BPD.getChiTietPhieuNhap(sophieunhap);
                    displayDataChiTietPhieuNhap(rs);
                    System.out.println("Xóa thành công!");
                } else {
                    System.out.print("Xóa bị lỗi!");
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXActionPerformed

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        BPhieuNhap BPN = new BPhieuNhap();
        if (radPhieu.isSelected()) {
            ResultSet rs = BPN.searchAllPhieuNhap(textTimKiem.getText());
            displayDataPhieuNhapHang(rs);
        } else if (tablePhieuNhap.getSelectedRow() >= 0) {
            ResultSet rs = BPN.searchAllChiTietPhieuNhapHang(String.valueOf(listPhieuNhap.get(tablePhieuNhap.getSelectedRow()).getSoPhieuNhap()), textTimKiem.getText());
            displayDataChiTietPhieuNhap(rs);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = tablePhieuNhap.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng có dữ liệu!", "Rỗng!", JOptionPane.ERROR_MESSAGE);
        } else if (0 == JOptionPane.showConfirmDialog(this, "Phiếu này đã có chi tiết phiếu nhập, bạn có muốn xóa toàn bộ chi tiết?", "Xóa", JOptionPane.OK_CANCEL_OPTION)) {
            BPhieuNhap PN = new BPhieuNhap();
            int sophieunhap = listPhieuNhap.get(index).getSoPhieuNhap();
            if (PN.XoaPhieuVaChiTietPhieuNhap(sophieunhap)) {
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!", "Đã xóa!", JOptionPane.INFORMATION_MESSAGE);
                buttonLamMoiActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Thao tác xóa thất bại!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonTru;
    private javax.swing.JButton buttonX;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JComboBox combMaDia;
    private javax.swing.JComboBox combNhaCungCap;
    private javax.swing.JComboBox combTenNhanVien;
    private javax.swing.JTextField ftextMaPhieuNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTenPhieu;
    private javax.swing.JLabel lblNgayLapPhieu;
    private javax.swing.JRadioButton radChiTietPhieu;
    private javax.swing.JRadioButton radPhieu;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tableChiTietPhieuNhap;
    private javax.swing.JTable tablePhieuNhap;
    private javax.swing.JTextField textTimKiem;
    // End of variables declaration//GEN-END:variables
}
